USE [Greek Airbnb];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
-- Run prepare_data.py first. Path is on the SQL Server machine.
-- For full data use the generated 02_load_csv.sql, which has exact source counts.
DECLARE @DataDir nvarchar(2000)=N'C:\airbnb_import\';
BEGIN TRY
BEGIN TRAN;
IF EXISTS(SELECT 1 FROM stg.Listings) OR EXISTS(SELECT 1 FROM stg.Reviews) OR EXISTS(SELECT 1 FROM stg.Bookings)
 THROW 50010,'Staging is not empty. Use a fresh project database.',1;
DECLARE @sql nvarchar(max);
SET @sql=N'BULK INSERT stg.Listings FROM '''+REPLACE(@DataDir+N'listings_import.csv',N'''',N'''''')+N''' WITH(FORMAT=''CSV'',FIRSTROW=2,FIELDQUOTE=''"'',FIELDTERMINATOR='','',ROWTERMINATOR=''0x0a'',CODEPAGE=''65001'',KEEPNULLS,TABLOCK);';
EXEC sys.sp_executesql @sql;
IF (SELECT COUNT_BIG(*) FROM stg.Listings)<>33 THROW 50011,'Imported row count mismatch: Listings. Use loader generated by prepare_data.py.',1;
SET @sql=N'BULK INSERT stg.Reviews FROM '''+REPLACE(@DataDir+N'reviews_import.csv',N'''',N'''''')+N''' WITH(FORMAT=''CSV'',FIRSTROW=2,FIELDQUOTE=''"'',FIELDTERMINATOR='','',ROWTERMINATOR=''0x0a'',CODEPAGE=''65001'',KEEPNULLS,TABLOCK);';
EXEC sys.sp_executesql @sql;
IF (SELECT COUNT_BIG(*) FROM stg.Reviews)<>1659 THROW 50011,'Imported row count mismatch: Reviews. Use loader generated by prepare_data.py.',1;
SET @sql=N'BULK INSERT stg.Bookings FROM '''+REPLACE(@DataDir+N'calendar_import.csv',N'''',N'''''')+N''' WITH(FORMAT=''CSV'',FIRSTROW=2,FIELDQUOTE=''"'',FIELDTERMINATOR='','',ROWTERMINATOR=''0x0a'',CODEPAGE=''65001'',KEEPNULLS,TABLOCK);';
EXEC sys.sp_executesql @sql;
IF (SELECT COUNT_BIG(*) FROM stg.Bookings)<>12045 THROW 50011,'Imported row count mismatch: Bookings. Use loader generated by prepare_data.py.',1;
COMMIT;
END TRY
BEGIN CATCH
IF @@TRANCOUNT>0 ROLLBACK;
THROW;
END CATCH;
GO
